### ISSUE TITLE
Error in validObject(.Object): grid is too coarse

### ISSUE THREAD

**Issue by mfansler** [alanocallaghan/scater#144]
I am trying to work with a SingleCellExperiment object:

```r
class: SingleCellExperiment 
dim: 39301 65068 
metadata(0):
assays(1): counts
rownames(39301): 0610009B22Rik.2 0610010F05Rik.1 ... Zzz3.2 Zzz3.3
rowData names(19): transcript_id transcript_gencode ... is_blacklisted is_consistent
colnames(65068): mESC_AAACCTGCAATCTGCA mESC_AAACCTGCACGGCTAC ...
  MEF_OSK_d8_TTTGTCAGTTGGTTTG MEF_OSK_d8_TTTGTCATCTTACCGC
colData names(6): cell_id sample_id ... detected_genes total
reducedDimNames(0):
altExpNames(0):
```

However, many multiple functions (e.g., `quickCluster`, `addPerCellQC`) fail with the error:

```r
# Error in validObject(.Object) : invalid class “RegularArrayGrid” object: 
#    grid is too coarse (all grid elements must have a length <=
#    .Machine$integer.max)
```

The reference to the machine's maximum representable integer leads me to suspect this has to do with the assay being too large. That is,

```r
39301*65068
# [1] 2557237468
```
which is larger than `.Machine$integer.max` (2,147,483,647).

The counts assay is a sparse matrix (257,141,456 non-zero entries), so it should still be valid to work with. 

Any idea what is going on? Is this a hard limit on the size SCE objects that Scater can work with?

---

## Session Info
```r
> sessionInfo()
R version 4.0.2 (2020-06-22)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: macOS Mojave 10.14.6

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Users/mfansler/miniconda3/envs/bioc_3_12/lib/libopenblasp-r0.3.12.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] parallel  stats4    stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] scDblFinder_1.4.0           ggbeeswarm_0.6.0            cowplot_1.1.0              
 [4] magrittr_2.0.1              forcats_0.5.1               stringr_1.4.0              
 [7] dplyr_1.0.5                 purrr_0.3.4                 readr_1.4.0                
[10] tidyr_1.1.3                 tibble_3.1.0                tidyverse_1.3.0            
[13] plyranges_1.10.0            scran_1.18.0                scater_1.18.0              
[16] ggplot2_3.3.3               Matrix_1.3-2                SingleCellExperiment_1.12.0
[19] SummarizedExperiment_1.20.0 Biobase_2.50.0              GenomicRanges_1.42.0       
[22] GenomeInfoDb_1.26.0         IRanges_2.24.0              S4Vectors_0.28.0           
[25] BiocGenerics_0.36.0         MatrixGenerics_1.2.0        matrixStats_0.58.0         

loaded via a namespace (and not attached):
 [1] colorspace_2.0-0          ellipsis_0.3.1            scuttle_1.0.0            
 [4] bluster_1.0.0             XVector_0.30.0            BiocNeighbors_1.8.0      
 [7] fs_1.5.0                  rstudioapi_0.13           farver_2.1.0             
[10] fansi_0.4.2               lubridate_1.7.10          xml2_1.3.2               
[13] sparseMatrixStats_1.2.0   knitr_1.31                jsonlite_1.7.2           
[16] Rsamtools_2.6.0           broom_0.7.5               dbplyr_2.1.0             
[19] compiler_4.0.2            httr_1.4.2                dqrng_0.2.1              
[22] backports_1.2.1           assertthat_0.2.1          limma_3.46.0             
[25] cli_2.3.1                 BiocSingular_1.6.0        htmltools_0.5.1.1        
[28] tools_4.0.2               rsvd_1.0.3                igraph_1.2.6             
[31] gtable_0.3.0              glue_1.4.2                GenomeInfoDbData_1.2.4   
[34] Rcpp_1.0.6                cellranger_1.1.0          vctrs_0.3.6              
[37] Biostrings_2.58.0         rtracklayer_1.50.0        DelayedMatrixStats_1.12.0
[40] xfun_0.20                 beachmat_2.6.0            rvest_1.0.0              
[43] lifecycle_1.0.0           irlba_2.3.3               statmod_1.4.35           
[46] XML_3.99-0.5              edgeR_3.32.0              zlibbioc_1.36.0          
[49] scales_1.1.1              hms_1.0.0                 yaml_2.2.1               
[52] gridExtra_2.3             stringi_1.5.3             BiocParallel_1.24.0      
[55] rlang_0.4.10              pkgconfig_2.0.3           bitops_1.0-6             
[58] evaluate_0.14             lattice_0.20-41           GenomicAlignments_1.26.0 
[61] labeling_0.4.2            tidyselect_1.1.0          R6_2.5.0                 
[64] generics_0.1.0            DelayedArray_0.16.0       DBI_1.1.1                
[67] pillar_1.5.1              haven_2.3.1               withr_2.4.1              
[70] RCurl_1.98-1.2            modelr_0.1.8              crayon_1.4.1             
[73] xgboost_1.3.3.1           utf8_1.1.4                rmarkdown_2.7            
[76] viridis_0.5.1             locfit_1.5-9.4            grid_4.0.2               
[79] readxl_1.3.1              data.table_1.14.0         reprex_1.0.0             
[82] digest_0.6.27             munsell_0.5.0             beeswarm_0.3.1           
[85] viridisLite_0.3.0         vipor_0.4.5 
```

**Comment by LTLA** [comment]
This is a **beachmat** problem that I'm pretty sure we fixed in 2.6.4.

**Comment by mfansler** [comment]
> This is a **beachmat** problem that I'm pretty sure we fixed in 2.6.4.

Okay, I'll try to update and check back. And thanks for the instant reply!

**Comment by mfansler** [comment]
Yes, that resolves it.

**Comment by zqsha** [comment]
I am now using beachmat v2.6.4, but the error is still there (below). Any thoughts of fixing it?

> qcstats <- perCellQCMetrics(sce) # doing QC for each spot
Error in validObject(.Object) : invalid class ?RegularArrayGrid? object: 
    grid is too coarse (all grid elements must have a length <= .Machine$integer.max)
> package.version("beachmat")
[1] "2.6.4"

**Comment by zqsha** [comment]
OK. Never mind. Solved! I need to reopen the R and Rstudio again.
